### PR TITLE
retry on no log resource found

### LINKED ISSUE #23: Intermittent test failure trying to read logs from CloudWatch
Copied from https://github.com/aws/amazon-cloudwatch-agent/issues/552 since the integ tests are in this repo now.

```
null_resource.integration_test (remote-exec):     cwl_util.go:62: Error occurred while getting log events: operation error CloudWatch Logs: GetLogEvents, https response error StatusCode: 400, RequestID: 9068b214-19ed-4ee9-beea-951cc1cdf4b7, ResourceNotFoundException: The specified log group does not exist.
```
can be seem sometimes from CloudWatch Logs integration tests. 

Should either:
- Poll for the existence of the log group before trying to get logs
- Retry the GetLogEvents call on ResourceNotFoundException

### PR DESCRIPTION
**Pull request by SaxyPandaBear**
# Description of the issue
Closes #23 

# Description of changes
Added a simple retry when attempting to get logs from CloudWatch results in a ResourceNotFoundException. 

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: test/cwl_util.go [hunk 1]
```diff
@@ -59,6 +58,14 @@ func ValidateLogs(t *testing.T, logGroup, logStream string, numExpectedLogs int,
 		output, err = cwlClient.GetLogEvents(*clientContext, params)
 
 		if err != nil {
+			var rnf *types.ResourceNotFoundException
+			if errors.As(err, &rnf) {
```
Comment (sky333999) [inline test/cwl_util.go:62]: Do we need a default max retry count before giving up?

Comment (SaxyPandaBear) [reply test/cwl_util.go:62]: Ah, you're right. I can fix that. I think 5 is a good round number. If the log group doesn't exist by then, something is up

**Review by sky333999 — DISMISSED** [review]

**Review by khanhntd — APPROVED** [review]

**Review by sky333999 — APPROVED** [review]

**Review by khanhntd — APPROVED** [review]
